### ISSUE TITLE
Stylelint 8.4.0 -> 9.0.0

### ISSUE THREAD

**Issue by fuhlig** [alexilyaev/stylelint-find-rules#13]
[Stylelint 9.0.0 Release](https://github.com/stylelint/stylelint/releases/tag/9.0.0)

**Comment by alexilyaev** [comment]
Thanks, will update.

Although, this only affects this package development, since it won't install `stylelint` for the user that installs this package (anything in `devDependencies` is ignored when you do `npm install -D stylelint-find-rules`)
