### ISSUE TITLE
Use require.resolve() instead of string concatenation

### ISSUE THREAD

**Issue by priver** [alexilyaev/stylelint-find-rules#21]
This package uses string concatenation to locate `README.md` file:
```js
const target = `stylelint/lib/rules/${ruleName}/README.md`;
const filePath = path.resolve(process.cwd(), 'node_modules', target);
```

But `node_modules` directory can be anyware else, e.g. if you are using yarn workspaces it is hoisted to project root.

You should use `require.resolve()` function to locate files:

```js
const target = `stylelint/lib/rules/${ruleName}/README.md`;
const filePath = require.resolve(target)
```

**Comment by alexilyaev** [comment]
Thanks for the feedback.

That looks like a good idea, I'll definitely give it a try.

Would it also work for globally installed packages like `npm i -g stylelint`?

I remember trying it out as part of https://github.com/alexilyaev/stylelint-find-rules/issues/17 and didn't manage to make it work with `yarn global add stylelint`.
