### ISSUE TITLE
  throw err;   ^

### ISSUE THREAD

**Issue by jitendravyas** [alexilyaev/stylelint-find-rules#6]
```
/Users/jitendravyas/app-v3/node_modules/stylelint-find-rules/src/lib/is-deprecated.js:7
  throw err;
```

```
Error: ENOENT: no such file or directory, open '/Users/jitendravyas/app-v3/node_modules/stylelint/lib/rules/block-no-single-line/README.md'
    at Error (native)
```

**Comment by alexilyaev** [comment]
This might be a version issue.

Can you tell me which version of `stylelint` you have?

**Comment by jitendravyas** [comment]
Latest version 8

**Comment by alexilyaev** [comment]
Oh, looks like it was removed in v8 so the file doesn't exist.  
I should check for file existence.  
For now you can see the list of removed rules here:  
https://github.com/stylelint/stylelint/blob/bd2e66e0167bc2062f0c3d57c871b3d26afd2469/CHANGELOG.md#800

**Comment by alexilyaev** [comment]
@jitendravyas  Actually, that doesn't make sense, the code gets the list of rules from Stylelint and for each rule finds it's readme file.  
`block-no-single-line` doesn't appear in the list of rules in v8 in the first place, so it shouldn't even get to that part of the code.

Can you tell me which version of `stylelint-find-rules` you've got?

**Comment by alexilyaev** [comment]
@jitendravyas can you try with the latest version?

**Comment by alexilyaev** [comment]
This should have been handled by latest versions, pls try to install the latest version.  
Let me know if the error still persists.
