### ISSUE TITLE
See if common Stylelint configs work properly with this tool

### ISSUE THREAD

**Issue by alexilyaev** [alexilyaev/stylelint-find-rules#7]
- https://github.com/stylelint/stylelint-config-recommended
- https://github.com/stylelint/stylelint-config-standard

**Comment by ntwb** [comment]
I believe the same results as seen in #8 would occur when using both shared configs linked in this issue

**Comment by alexilyaev** [comment]
I"m not sure, since you'd need a config to define that you're extending these configs.

**Comment by ntwb** [comment]
The same results occur, I just committed and created a new branch here:
> https://github.com/stylelint/stylelint-config-standard/tree/stylelint-find-rules

Here is the specific commit I created to test this:
> https://github.com/stylelint/stylelint-config-standard/commit/8e053cf16d67897856900819c64809b2a89af9e1

**Comment by alexilyaev** [comment]
Like I mentioned in #8 , it doesn't find a Stylelint config per cosmicconfig (e.g. `.stylelintrc` or `stylelint.config.js`, etc.).  
I'll handle it by telling the user a config was not found.

**Comment by alexilyaev** [comment]
I understand that in your repo the config is in `index.js`, but that's not how a user will use this package. So cosmicconfig is the logical way since Stylelint itself uses it.

**Comment by alexilyaev** [comment]
[v0.8.0](https://github.com/alexilyaev/stylelint-find-rules/releases/tag/v0.8.0) now looks through the configs in `extends` and excludes their rules from the results.

**Comment by ntwb** [comment]
Works great @alexilyaev 👌
